server:
  port: 8000
  servlet:
    context-path: /tool
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpth:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html

